*   Python List: 행렬 연산을 위해 for 문 사용
*   Numpy : 차원이 다른 행렬 간에도 연산이 가능
*   Tensor : GPU 상에서 연산이 가능하고 autograd(자동 미분)연산 기능이 있는 자료형

## 1. Python List와 Numpy의 행렬 연산

In [2]:
import numpy as np

data = [1, 2, 3, 4, 5]
data2 = [1, 3, 5, 7, 9]

In [3]:
## python의 list는 연산의 결과로 concatination이 이루어진다
print(data * 2)
print(data + data2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 3, 5, 7, 9]


In [4]:
## 반면 numpy의 ndarray를 통한 연산은 행렬 연산으로 수행된다.
print(np.array(data) * 2)
print(np.array(data) + np.array(data2))

[ 2  4  6  8 10]
[ 2  5  8 11 14]


In [5]:
## 만약 python의 list에서 행렬 연산을 하려고 한다면 for문을 이용해야 한다
print([i * 2 for i in data])
print([data[i] + data2[i] for i in range(len(data))])

[2, 4, 6, 8, 10]
[2, 5, 8, 11, 14]


## 2. Tensor의 생성 및 초기화

In [6]:
import torch
import numpy as np

# 초기화되지 않은 행렬 생성
x = torch.empty(5,3)
y = np.empty((5, 3))
print(x)
print(y)

tensor([[ 2.6654e+27,  4.4362e-41,  2.6654e+27],
        [ 4.4362e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  1.0551e+24],
        [ 4.5407e+24,  1.7836e+25,  1.0305e+21],
        [ 6.9474e+22, -1.7127e+16,  1.8491e+31]])
[[4.67694891e-310 0.00000000e+000 2.12199579e-314]
 [4.64502546e+151 4.35180602e+276 1.45349864e-094]
 [2.04738726e+190 1.43393751e+166 8.76132466e+245]
 [9.31733870e+242 1.92393181e+227 1.39635045e-308]
 [4.94065646e-323 6.71785340e-310 6.32404027e-322]]


In [7]:
# torch.rand : 0 ~ 1 사이의 랜덤 초기화 행렬 생성
x = torch.rand(5,3)
print(x)

tensor([[0.2704, 0.3116, 0.9796],
        [0.4378, 0.8597, 0.6069],
        [0.2237, 0.1299, 0.1311],
        [0.5478, 0.2796, 0.9749],
        [0.7432, 0.7519, 0.5481]])


In [8]:
# 행렬에 대한 기술 통계 값 출력 가능
x.mean(), x.std()

(tensor(0.5197), tensor(0.2937))

In [9]:
# torch.randn : 정규 분포에서 랜덤 초기화한 행렬 생성
y = torch.randn(5, 3)
print(y)

tensor([[-0.6750,  0.4258,  0.4279],
        [-0.1215,  1.6424, -1.0874],
        [-0.3644,  1.7714,  2.3071],
        [ 0.1589, -0.5366,  0.7112],
        [ 0.0588,  1.0674, -0.1017]])


In [10]:
y.mean(), y.std() # 정규 분포인 만큼 평균은 0, 표준편차는 1에 가까운 것을 확인할 수 있다

(tensor(0.3789), tensor(0.9683))

In [11]:
# 특정 값을 tensor로 만들기
z = torch.tensor([[1.2, 4.5],[1, 2]])
z

tensor([[1.2000, 4.5000],
        [1.0000, 2.0000]])

## 3. Tensor size & Numpy 변환

In [12]:
# x.size() : Tensor의 size 확인
x = torch.randn(3,4)
print(x)
print("x size : ", x.size())

tensor([[-0.3344,  1.3915, -0.9406, -0.7495],
        [-0.2305,  0.3313, -0.8857,  0.9780],
        [-0.2604, -1.4590,  0.3771, -0.5475]])
x size :  torch.Size([3, 4])


In [13]:
# Tensor의 size를 변경하는 방법 1: reshape (for any tensor)

x = torch.rand(3,4)  # 3행 4열
y = x.reshape(4,3)   # 4행 3열
z = x.reshape(-1, 2) # 2열로 하고 -1에는 남은 값을 자동으로 할당
print(x, x.size(), "\n", y, y.size(), "\n", z, z.size())

tensor([[0.9784, 0.1346, 0.5678, 0.8484],
        [0.1223, 0.2909, 0.1693, 0.4076],
        [0.2698, 0.0878, 0.1638, 0.7548]]) torch.Size([3, 4]) 
 tensor([[0.9784, 0.1346, 0.5678],
        [0.8484, 0.1223, 0.2909],
        [0.1693, 0.4076, 0.2698],
        [0.0878, 0.1638, 0.7548]]) torch.Size([4, 3]) 
 tensor([[0.9784, 0.1346],
        [0.5678, 0.8484],
        [0.1223, 0.2909],
        [0.1693, 0.4076],
        [0.2698, 0.0878],
        [0.1638, 0.7548]]) torch.Size([6, 2])


In [14]:
# Tensor의 size를 변경하는 방법 2: view (for contiguous tensors)

x = torch.randn(3,4) # Normal distribution (정규 분포의 값으로 난수 생성)
y = x.view(4,3)
z = x.view(-1, 2)
print(x, x.size(), "\n", y, y.size(), "\n", z, z.size())

tensor([[ 0.0531, -1.0366,  1.5609, -0.1091],
        [ 1.2514, -1.4886, -0.0806, -1.2384],
        [-1.2985, -0.5400,  0.5532,  0.1901]]) torch.Size([3, 4]) 
 tensor([[ 0.0531, -1.0366,  1.5609],
        [-0.1091,  1.2514, -1.4886],
        [-0.0806, -1.2384, -1.2985],
        [-0.5400,  0.5532,  0.1901]]) torch.Size([4, 3]) 
 tensor([[ 0.0531, -1.0366],
        [ 1.5609, -0.1091],
        [ 1.2514, -1.4886],
        [-0.0806, -1.2384],
        [-1.2985, -0.5400],
        [ 0.5532,  0.1901]]) torch.Size([6, 2])


#### reshape과 view의 차이점
모양 변경의 유연성   
view는 tensor의 연속적인 부분을 다른 차원으로 재배치할 때만 가능     
반면 reshape은 어느 tensor에 대해서도 재배치 가능  
cf) 연속적(contiguous)는 axis 순서대로 자료가 저장된 상태를 의미한다   

In [15]:
y = torch.ones(3, 4)
print(y, '\n', y.is_contiguous(), '\n') # 값이 저장된 순서대로이므로 연속적인 상태

y.transpose_(0, 1) # transpose를 통해 값이 저장된 순서를 조작
print(y, '\n', y.is_contiguous()) # 연속적이지 않은 상태가 되었다

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 
 True 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 
 False


In [16]:
y.reshape(3, 2, 2)  # 실행 가능
#y.view(3, 2, 2)    # 실행 불가 --> "view size is not compatible with input tensor's size and stride"라는 RuntimeError 발생

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [17]:
# Tensor to numpy
x = torch.ones(5)
y = x.numpy()
print(x, type(x))
print(y, type(y))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


In [18]:
# Numpy to tensor
x = np.ones(5)
y = torch.from_numpy(x)
print(x, type(x))
print(y, type(y))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'torch.Tensor'>


In [19]:
# GPU 연산을 위한 CUDA tensor
x = torch.ones(5)
y = x.to(device="cuda:0") #런타임 연결 gpu로 설정
print(x)
print(y)

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.], device='cuda:0')


## 4. Tensor Autograd

* requires_grad를 true로 세팅하면 tensor에 대한 모든 연산 추적 가능

* 이를 통해 forward propagation 후, .backward() 호출 시 모든 gradient 자동으로 계산

In [21]:
x = torch.tensor(([1., 2.], [3., 4.]), requires_grad=True) # requires_grad를 해야 기록한다
print(x)
y = 3 * ((x+2)**2)
print(y)

out = y.sum()
print(out)

out.backward()
print(x.grad)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)
tensor(258., grad_fn=<SumBackward0>)
tensor([[18., 24.],
        [30., 36.]])


마지막 out.backward()로 역전파를 수행하게 된다.   
그리고 나서 출력한 x.grad는 x에 대한 변화도를 나타낸다.  
즉 [1, 2, 3, 4]가 각각 어떠한 변화를 갖게 되었는지를 역전파를 통해 계산된 결과를 출력한 것이다   
이는 y의 식을 x에 대해 미분하면 되는 것이고 3 * ((x+2) **2)이므로   
x에 대해 미분하면 6 * (x + 2)가 될 것이다.   
따라서 x.grad의 출력 결과를 보면 6 * (x + 2)와 동일하다는 것을 알 수 있다.

In [24]:
print(6 * (x+2))

tensor([[18., 24.],
        [30., 36.]], grad_fn=<MulBackward0>)
